#!/bin/bash

# my personal configuration

#export PATH
#unset USERNAME
#umask 002

export HISTFILE=~/.sh_history
export HISTSIZE=100000
export HISTFILESIZE=100000

# tell bash to understand emacs commands
set -o emacs

alias rm='rm -i'
alias mv='mv -i'
alias l='ls -hl'
alias la='l -a'
alias le='less'
alias tl='tail'
alias tf='tail -f'

# vim
alias v='vim'
alias vd='vimdiff'

# emacs
alias e='emq'
alias E='emacs'

# invoke ediff just like vimdiff
alias ed='ediff'

alias c='clear'
alias j='jobs'
alias g='grep --color=auto -n'
alias gr='grep --color=auto -n -R'
alias ge='grep --color=auto -n -E'

# using screen
alias sc='screen'
alias scr='screen -r'
