#!/bin/bash

# my personal configuration

#export PATH
#unset USERNAME

umask 002
unlimit

PATH=~/private/elasticsearch-6.6.2/bin:~/private/bin:~/private/emacs-26.1/bin:~/private/ag-2.0.0/bin:~/private/gtags-6.5.7/bin: \
    $(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin/:~/private/unrar/bin:$PATH

source ~/private/bin/function

export HISTFILE=~/.sh_history
export HISTSIZE=100000
export HISTFILESIZE=100000

# addtional searche path for gtags tag file
# "gtags" should be executed at each directory in the GTAGSLIBPATH
export GTAGSLIBPATH=~/my_tag_files:/usr/src/lib

# compile options for PCRE
export PCRE_LIBS="-L~/private/pcre2-10.32/lib -lpcre"
export PCRE_CFLAGS=-I~/private/pcre2-10.32/include/pcre

# compile options for XZ
export LZMA_LIBS="-L~/private/xz-5.2.4/lib -llzma"
export LZMA_CFLAGS=-I~/private/xz-5.2.4/include

# Golang environment variables
export GOPATH=~/workspace/go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# $GOPATH/src : where your Go projects / programs are located
# $GOPATH/pkg : contains every package objects
# $GOPATH/bin : the compiled binaries home

# see most used commands in history, use $2 on csh instead of $3.
alias statis="history | awk '{print $3}' | sort | uniq -c | sort -rn | head"

# git operation.
alias gts='git pull --rebase && git submodule update --init'
alias ga='git add'
alias gd='git diff'
alias gm='git commit --amend'
alias gt='git st'
alias gp='git push origin HEAD:refs/for/master/master'

# tell bash to understand emacs commands
set -o emacs

alias rm='rm -i'
alias mv='mv -i'
alias l='ls -hl'
alias la='l -a'
alias le='less -R'
alias tl='tail'
alias tf='tail -f'

# vim
alias v='vim'
alias vd='vimdiff'

# emacs
alias e='emq'
alias E='emacs'

# invoke ediff just like vimdiff
alias ed='ediff'

alias c='clear'
alias j='jobs'
alias g='grep --color=always -n -E'
alias gi='grep --color=always -n -E -i'
alias gr='grep --color=always -n -E -R'
alias gv='grep --color=always -n -E -v'

# using screen
alias sc='screen'
alias scr='screen -d -r'
